---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by marui.
--- DateTime: 2023/6/8 22:07
---
--比较线程标识是否相同
if (redis.call('get', KEYS[1]) == ARGV[1]) then
    --释放锁 del key
    return redis.call("del", KEYS[1])
end
return 0